<?php $obj = $this->datos; ?>
<div class="box-header navbar-inner">
	<h3><button class="btn btn closeform" title="Atras"><i class="icon-step-backward"></i></button><span class="break"></span> Información de Estados de madurez</h3>
    <div class="box-icon btn-group">
    	<button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>
    </div>
</div>
<div class="box-content">
	<table class="table table-condensed table-striped">
		<tr>
			<td>
				<b>Nombre: </b></td>
			<td>
			<?php echo $obj->getNombre(); ?>	
			</td>
		</tr>
	</table>
 </div>
