<script>
	$(document).ready(function(){
		$("#retomodalbuscar").modal('hide');
		reloadgrid();
	});
	function retoindexexcel(){

		var form = $('form#retoformbuscar');
		if($('input#download').length == 0){
			form.append('<input type="hidden" id="download" name="download" value="1" />"');
		}
		var formData = form.serialize();
		$('form#retoformbuscar').submit();
		form.find('input#download').remove();
	}
</script>
<div id="retoindex" class="box  contentindex"  filterreceived="<?php echo $this->filterreceived; ?>" request="<?php echo $this->baseUrl() ?>/reto/reto/index<?php echo $this->filterreceived; ?>">
    <div class="box-header navbar-inner">
        <h3><span class="hidden-phone"><i class="icon-align-justify"></i><span class="break"></span> Listado </span>Reto</h3>
        <div class="box-icon btn-group">
                <a class="btn" type="button" title="Buscar"  href="#retomodalbuscar" data-toggle="modal" > <i class="icon-search"></i> </a>
            <?php if($this->permisos["add"]): ?>
                <a id="newreto" href="#newreto" class="btn btn-info loadform" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/add<?php echo $this->filterreceived; ?>" > <i class="icon-plus"></i></a>
            <?php endif ?>
                <button class="btn btn-warning" title="Descargar a Excel" onclick="retoindexexcel()" type="button"><i class="icon-download-alt"></i></button>
                <!-- <button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>-->
        </div>
    </div>
    <div class="box-content">
<table id="retoTable" class="table table-striped table-condensed " formBuscar="retoformbuscar" >
<thead >
	<tr>
		<th  class="sort " sort="titulo" >Título</th>
		<th  class="sort " sort="descripcioncorta" >Descripciòn corta</th>
		<th  class="sort hidden-phone" sort="fechainicio" >Fecha de inicio</th>
		<th  class="sort hidden-phone" sort="fechafin" >Fecha de finalizaciòn</th>
		<th  class="sort hidden-phone" sort="estado" >Estado del reto</th>
		<th>Solucionadores</th>
		<th class="no-print" width="126px">Acciones</th>

	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination->_objects as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getTitulo(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getDescripcioncorta(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getFechainicio(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getFechafin(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getEstadoObject()->get_Label_model(); ?>
		</td>
		<td>
			<?php if($obj->getConteosolucionadores() > 0): ?>
				<a title="Solucionadores" class="btn btn-inverse" type="button" href="<?php echo $this->baseUrl() ?>/reto/solucionadores/byreto/reto/<?php echo $obj->getId() ?>" ><i class="icon-lightbulb"></i></a>
			<?php endif ?>
		</td>
		<td class="no-print" >
		  <div class="btn-group" title="<?php echo $obj->get_Label_Model() ?>">
			<?php if($this->permisos["edit"]  ): ?>
				<button title="Editar" class="btn btn-success loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/edit/id/<?php echo $obj->getId() ?>" ><i class="icon-pencil"></i></button>
			<?php endif ?>
			<?php if($this->permisos["detail"] ): ?>
				<button title="Detalles" class="btn btn-info loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/detail/id/<?php echo $obj->getId() ?>"><i class="icon-fullscreen"></i></button>
			<?php endif ?>
			<?php if($this->permisos["delete"]  ): ?>
				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/delete/id/<?php echo $obj->getId() ?>"><i class="icon-trash"></i></button>
			<?php endif ?>
            </div>
		</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>
    <?php echo $this->paginationControl($this->pagination,'Sliding','pagination.phtml');?>
    </div>
		<div class="modal hide" id="retomodalbuscar">
		    <div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
		    <h3>Buscar</h3>
		    </div>
		    <div class="modal-body">
				<?php echo $this->formBuscar;?>
			</div>
			<div class="modal-footer">
			</div>
		</div>
</div>
<div ><ul id="progreso"></ul></div>

<script type="text/javascript">
	$(document).ready(function(){
		for (var i = 8 - 1; i > 0; i--) {
		$.get('http://veolia/public/reto/solucionadores/getprogreso', {solucion: 2, seccion: i},function (data) {
				$("#progreso").append('<li>'+
									'progreso: '+data.progreso+'<br>'+
									'progresoEsperado: '+data.progresoEsperado+'<br>'+
									'conteo: '+data.conteo+'<br>'+
									'seccion: '+data.seccion+'<br>'+'</li>');
			});
		}
	});
</script>