<div class="bigtitle">
	<br><br><br><br>
	<br><br><br><br>
	<h1>CAPITULO 1</h1><hr><h2>Introducción</h2>
</div>
<pagebreak />
<h3>Introduccion</h3>
<p align="justify">Este manual tiene la finalidad de servir como guia para el Usuario del Sistema que la Institucion usuaria de celufutbol. Los procesos aqui descritos, como podra darse cuenta el lector, son muy sencillos dado que la interfaz de usuario es muy amigable y requieren un minimo de habilidades para utilizarla. Es muy importante que conserve en lugar seguro las cuentas de usuario y sus contraseñas de acceso al sistema de tal forma que evite que personal no autorizado obtenga informacion de sus unidades. Se espera que este manual le sea de gran ayuda.</p>

<pagebreak />

<pagebreak />
<div class="bigtitle">
	<br><br><br><br>
	<br><br><br><br>
	<h1>CAPITULO 2</h1><hr><h2>Acceso al sistema</h2>
</div>
<pagebreak />
<h3>- Acceso al sistema</h3>
<p align="justify">En esta sección se le proporcionará al lector la información necesaria para que ingrese al sistema, así como los pasos requeridos. Los conocimientos mínimos que deben tener las personas que operan esta plataforma y utilizarán este manual son:</p>
<ul>
	<li>Conocimientos básicos acerca de Programas Utilitarios.</li>
	<li>Conocimientos básicos de Navegación en Web.</li>
	<li>Conocimiento básico de Internet.</li>
	<li>Conocimiento básico de Windows.</li>
</ul>
<h4>Datos</h4>
<p align="justify">Los datos necesarios para ingresar al sistema son:</p>
	a) Nombre de usuario.<br>
	b) Contraseña.<br>
<br>
<p align="justify">Estos datos le son proporcionados por parte del personal administrador al momento en que se contraten los servicios.</p>
<p align="justify">Si por alguna razón usted extraviara o no recordara estos datos, siempre podrá solicitarlos en la página de inicio en el enlace "¿No recuerda su contraseña?" o solicitarlo a los administradores. Al momento de solicitar dicha información, es necesario que se proporcione los datos generales que se le lleguen a preguntar.</p>
<h4>Ingreso</h4>
<p align="justify">Para ingresar, por favor siga los siguientes pasos:</p>
<ol>
<li>Abra su navegador de internet (preferiblemente firefox o chrome)</li>
<li>Diríjase a la dirección www.veolia.com</li>
<li>Proporcione los datos solicitados de usuarios y contraseña y de click en el botón  ingresar </li>
</ol>
<img src="<?php echo($this->baseUrl()); ?>/img/ayuda/login.png">
<pagebreak />
<div class="bigtitle">
	<br><br><br><br>
	<br><br><br><br>
	<h1>CAPITULO 3</h1><hr><h2>Módulos del sistema</h2>
</div>
<pagebreak />
<h3>- Modulos del sistema</h3>
la plataforma esta dividida en los siguientes modulos

