<!DOCTYPE html>
<html lang="en">
<head>
<title>Manual de usuarios</title>
<link href="<?php echo $this->baseUrl() ?>/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl() ?>/css/stylepdf.css" rel="stylesheet"> 
<!-- <link href="<?php echo $this->baseUrl() ?>/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl() ?>/css/stylefet.css" rel="stylesheet"> -->
</head>	
	<body>
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
		<div class="bigtitle"><img src="<?php echo($this->baseUrl()); ?>/img/logo.png">
			<hr><br><br><br><br>
			<h1>Bienvenido</h1><br><br>
			<h2>Manual de Usuario</h2>
		</div>
