<a data-toggle="modal" id="addnewindicadores" href="#newindicadores" class="btn btn-primary bg-color-4 pull-right addaction" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/add<?php echo $this->filterreceived; ?>" > <i class="fa fa-plus"></i> Agregar</a>

<table id="indicadoresTable" class="table table-striped table-condensed " formBuscar="indicadoresformbuscar" >
<thead >
	<tr>
		<th class="">Indicador</th>
		<th class="hidden-phone">Descripción </th>
		<th style=" width: 74px;"></th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getIndicador(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getDescripcion(); ?>	
		</td>
		<td class="no-print pull-right" >

				<a data-toggle="modal" href="#newindicadores" class="btn btn-success editaction" title="Editar" type="button" iditem="<?php echo $obj->getId() ?>" request="<?php echo $this->baseUrl() ?>/reto/indicadores/listbyid/id/<?php echo $obj->getId() ?>" >&nbsp;&nbsp;<i class="fa fa-pencil"></i>&nbsp;&nbsp;</a>

				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/indicadores/delete/id/<?php echo $obj->getId() ?>">&nbsp;&nbsp;<i class="fa fa-trash"></i>&nbsp;&nbsp;</button>

		</td>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>

<!--  MODAL indicadores-->
  <div class="modal fade customModal" id="newindicadores" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-4 border-color-1">
            <h3 class="panel-title modtitle">Nuevo Indicador</h3>
          </div>
          <div class="panel-body">
            <form action="#" name="indicadoresform" id="indicadoresform" method="POST" role="form">
            	<!-- id hidden para la edicion -->
              <div class="form-group formField">
              	<input type="hidden" class="form-control" name="indicadores_id" id="indicadores_id">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" name="indicador" id="indicador" placeholder="Indicador">
              </div>
              <div class="form-group formField">
              	<textarea name="descripcion" rows="2" id="descripcion" placeholder="Descripcion" class="form-control"></textarea>
              </div>
              <div class="form-group formField">
                <a id="saveindicadores" data-dismiss="modal" href="#newindicadores" class="btn btn-primary btn-block bg-color-3 border-color-3">Agregar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript"></script>