<!-- WHITE SECTION -->
<section class="whiteSection full-width clearfix eventSection" id="ourEvents">
  <div class="container">
    <div class="sectionTitle text-center">
      <h2>
        <span class="shape shape-left bg-color-4"></span>
        <span>Retos</span>
        <span class="shape shape-right bg-color-4"></span>
      </h2>
    </div>

    <div class="row">
      <?php foreach ($this->pagination as  $key => $obj) : ?>
        <div class="col-sm-6 col-xs-12 block">
          <div class="media eventContent bg-color-<?php echo $key+1; ?>">
            <div class="media-left">
              <img class="media-object" src="<?php echo $obj->getImagen(); ?>" alt="Image">
              <span class="sticker-round <?php if($obj->getEstado()==2){echo "bg-color-3";}?>"><?php echo $obj->getEstadoObject()->get_Label_model(); ?></span>
            </div>
            <div class="media-body">
              <h3 class="media-heading"><a href="single-event-left-sidebar.html"><?php echo $obj->getTitulo(); ?></a></h3>
              <ul class="list-unstyled">
                <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechainicio(); ?></li>
                <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechafin(); ?></li>
              </ul>
              <p><?php echo $obj->getDescripcioncorta(); ?></p>
              <ul class="list-inline btn-yellow">
                <li><a href="<?php echo $this->baseUrl()?>/index/reto/id/<?php echo $obj->getId(); ?>" class="btn btn-primary">Ver más</a></li>
              </ul>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
     <!--  <div class="col-sm-6 col-xs-12 block">
        <div class="media eventContent bg-color-2">
           <div class="media-left">
            <img class="media-object" src="img/home/event/event-2.jpg" alt="Image">
            <span class="sticker-round">Pendiente</span>
          </div>
          <div class="media-body">
            <h3 class="media-heading"><a href="single-event-left-sidebar.html">Reto 2</a></h3>
            <ul class="list-unstyled">
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 2 de febrero</li>
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de febrero</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
            <ul class="list-inline btn-green">
              <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12 block">
        <div class="media eventContent bg-color-3">
          <div class="media-left">
            <img class="media-object" src="img/home/event/event-3.jpg" alt="Image">
            <span class="sticker-round bg-color-3">Cerrado</span>
          </div>
          <div class="media-body">
            <h3 class="media-heading"><a href="single-event-left-sidebar.html">Nunc suscipit sem et.</a></h3>
            <ul class="list-unstyled">
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 1 de Enero</li>
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de Enero</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
            <ul class="list-inline btn-red">
              <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12 block">
        <div class="media eventContent bg-color-4">
           <div class="media-left">
            <img class="media-object" src="img/home/event/event-4.jpg" alt="Image">
            <span class="sticker-round">Pendiente</span>
          </div>
          <div class="media-body">
            <h3 class="media-heading"><a href="single-event-left-sidebar.html">Reto n</a></h3>
            <ul class="list-unstyled">
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 1 de Enero</li>
              <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de Enero</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
            <ul class="list-inline btn-sky">
              <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
            </ul>
          </div>
        </div>
      </div> -->
    </div>
  </div>
</section>
<!-- 
<script> 
$(document).ready(function(){
  loadpage(); 


  reloadactividadesfundamentales();
})
function clicksaveformactividadesfundamentales()
{
  var buttonSelect = $(this); 
  buttonSelect.parents(".form-actions").find("button").button('loading');
  if ($("#actividadesfundamentalesform").valid()) {
    $.post("<?php echo $this->baseUrl()?>/reto/actividadesfundamentales/add", $("#actividadesfundamentalesform").serialize(),
      function(data) {
        if (data.id<0) {
          $("#actividadesfundamentalesform").parent().html(data.form);          
          reloadactividadesfundamentales();
          buttonSelect.parents(".form-actions").find("button").button('reset');
        } else {
              $('.notify').notify({message: { text: '  Registro agregado con éxito ' }}).show();
              show_loader();                        
                    var Request = "";
                    if (buttonSelect.attr("new") == "true") {
            var Content = buttonSelect.parents(".contenido");
                        Request = "<?php echo $this->baseUrl()?>/reto/actividadesfundamentales/add<?php echo $this->filterreceived?>";
                        Content.load(Request,function(response, status, xhr) {successload(response, status, xhr)});
                    } else {
                         history.back();
                         hide_loader();
                    }
        }
      }
    )
  } else {
    buttonSelect.parents(".form-actions").find("button").button('reset');
    alert("Formulario invalido");
  }
}
function reloadactividadesfundamentales(){
  $("#submitactividadesfundamentales").click(clicksaveformactividadesfundamentales);
}
</script> -->
