<!-- WHITE SECTION -->
<section class="whiteSection full-width clearfix eventSection" id="ourEvents">
  <div class="container">
   <?php 
      if(Zend_Auth::getInstance()->hasIdentity()){
      ?>
      <div class="col-xs-12">
        <div class="lowerPartTitle footerInfo">
          <h4>Mis retos</h4>
          <p>
            <ul class="list-unstyled para-list">
             <?php foreach ($this->misretos as  $key => $objmisretos) : ?>
              <li><i class="fa fa-angle-double-right"></i><a href="<?php echo $this->baseUrl()?>/index/solucion/id/<?php echo $objmisretos->getReto(); ?>" class="btn btn-link">
              <?php echo $objmisretos->getRetoObject()->get_Label_model(); ?></a></li>
              <?php endforeach; ?>
            </ul>
          </p>
        </div>
      </div>
       <?php 
         }
    ?>
    <div class="sectionTitle text-center">
      <h2>
        <span class="shape shape-left bg-color-4"></span>
        <span>Retos activos</span>
        <span class="shape shape-right bg-color-4"></span>
      </h2>
    </div>

    <div class="row">
    <div class="col-sm-3 col-xs-12 block">
    </div>
      <?php foreach ($this->pagination as  $key => $obj) : ?>
        <!-- <div class="col-sm-6 col-xs-12 block">
          <div class="media eventContent bg-color-<?php echo $key+1; ?>">
            <div class="media-left">
              <img class="media-object" src="<?php echo $obj->getImagen(); ?>" alt="Image">
              <span class="sticker-round <?php if($obj->getEstado()==2){echo "bg-color-3";}?>"><?php echo $obj->getEstadoObject()->get_Label_model(); ?></span>
            </div>
            <div class="media-body">
              <h3 class="media-heading"><a href="single-event-left-sidebar.html"><?php echo $obj->getTitulo(); ?></a></h3>
              <ul class="list-unstyled">
                <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechainicio(); ?></li>
                <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechafin(); ?></li>
              </ul>
              <p><?php echo $obj->getDescripcioncorta(); ?></p>
              <ul class="list-inline btn-yellow">
                <li><a href="<?php echo $this->baseUrl()?>/index/reto/id/<?php echo $obj->getId(); ?>" class="btn btn-primary">Ver más</a></li>
              </ul>
            </div>
          </div>
        </div> -->
        <div class="col-sm-6 col-xs-12 block">
            <?php 
              if( strlen($obj->getImagen())>0){ 
              $filename = $obj->getImagen();
              $archivo = $filename;
              $extension = end(explode('.',$archivo));
              $nuevo_nombre = $obj->getId().'.'.$extension;
            }else{
              $nuevo_nombre = '';
            }
            ?>
            <div class="thumbnail thumbnailContent">
              <a href="<?php echo $this->baseUrl()?>/index/reto/id/<?php echo $obj->getId(); ?>"><img src="<?php echo $this->baseUrl()?>/Files/retoimagen/<?php echo $nuevo_nombre; ?>" alt="image" class="img-responsive"></a>
              <div class="sticker-round bg-color-4"><?php echo $obj->getEstadoObject()->get_Label_model(); ?></div>
              <div class="caption border-color-4">
                <h3><a href="single-blog-left-sidebar.html" class="color-4"><?php echo $obj->getTitulo(); ?></a></h3>
                <ul class="list-inline">
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechainicio(); ?></li>
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo $obj->getFechafin(); ?></li>
                </ul>
                <p><?php echo $obj->getDescripcioncorta(); ?>...</p>
                <ul class="list-inline btn-red">
                  <li><a href="<?php echo $this->baseUrl()?>/index/reto/id/<?php echo $obj->getId(); ?>" class="btn btn-link"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Ver Mas</a></li>
                </ul>
              </div>
            </div>
          </div>
      <?php endforeach; ?>
    </div>
  </div>
</section>

