<?php $obj = $this->datos; ?>
 <!-- MAIN SECTION -->
    <section class="mainContent full-width clearfix courseSingleSection">
      <div class="container">
        <div class="row">
          <div class="col-md-9 col-sm-8 col-xs-12 block">
            <div class="thumbnail thumbnailContent alt">
            	<object width="100%" height="385"
					data="https://www.youtube.com/embed/XGSy3_Czz8k">
				</object>
              <div class="caption border-color-1">
                <h3 class="color-1"><?php echo $obj->getTitulo(); ?></h3>
                <p><?php echo $obj->getDescripcioncompleta(); ?></p>
              </div>
            </div>
            <?php
	            if(Zend_Auth::getInstance()->hasIdentity()){
	              ?>
	                <div class="btnArea">
		              <a href="<?php echo $this->baseUrl()?>/index/solucion/id/<?php echo $obj->getId(); ?>" class="btn btn-primary">Aplicar</a>
		            </div>
	              <?php 
	              
	            }else{
	              ?>
	              	<div class="btnArea">
		              <a href="<?php echo $this->baseUrl()?>/authentication/login?mensaje=login" class="btn btn-primary">Aplicar </a>
		            </div>
	            <?php 
	            }
            ?>
            
          </div>
          <div class="col-md-3 col-sm-4 col-xs-12">
            <aside>
              <div class="rightSidebar">
                <div class="panel panel-default">
                  <div class="panel-heading bg-color-1 border-color-1">
                    <h3 class="panel-title">Información general</h3>
                  </div>
                  <div class="panel-body">
                    <ul class="media-list">
                      <li class="media">
                        <div class="media-left iconContent bg-color-2">
                          <i class="fa fa-calendar" aria-hidden="true"></i>
                        </div>
                        <div class="media-body iconContent">
                          <h4 class="media-heading color-2">Fecha de inicio</h4>
                          <p><?php echo $obj->getFechainicio(); ?></p>
                        </div>
                      </li>
                      <li class="media">
                        <div class="media-left iconContent bg-color-4">
                          <i class="fa fa-calendar" aria-hidden="true"></i>
                        </div>
                        <div class="media-body iconContent">
                          <h4 class="media-heading color-4">Fecha de fin</h4>
                          <p><?php echo $obj->getFechafin(); ?></p>
                        </div>
                      </li>
                      <li class="media">
                        <div class="media-left iconContent bg-color-3">
                          <i class="fa fa-anchor" aria-hidden="true"></i>
                        </div>
                        <div class="media-body iconContent">
                          <h4 class="media-heading color-3">Estado</h4>
                          <p><?php echo $this->datos->getEstadoObject()->get_Label_model(); ?></p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                
              </div>
            </aside>
          </div>
        </div>
      </div>
    </section>
