<div class="row">
  <div class="col-sm-6 col-xs-12">
    <div class="accordionCommon" id="accordionOne">
      <div class="panel-group" id="accordionFirst">
        <div class="panel panel-default">
          <label class="panel-heading bg-color-1" >
            <span>Manejo de datos de contacto:</span>
          </label>                    
          <div id="collapse-aa" class="panel-collapse collapse in">
            <div class="panel-body">
              <p>La Cámara de Comercio de Armenia y del Quindío  se permite informarle que los datos personales  que se relacionen a continuación tales como nombres, apellidos, dirección de residencia, números de teléfono, celular y correo electrónico, se mantendrán en estricta confidencialidad y no serán utilizados para fines distintos a los de la presente convocatoria, es decir que no se compartirán con terceros.</p>
              <p>El usuario podrá rectificar, actualizar o suprimir sus datos personales, enviando un mensaje de correo electrónico a  retocamaraarmenia@corporacionenlace.org o telefónicamente a la línea  320 831 2489.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-xs-12">
    <div class="accordionCommon" id="accordionOne">
      <div class="panel-group" id="accordionFirst">
        <div class="panel panel-default">
          <label class="panel-heading bg-color-1" >
            <span>Divulgación de la postulación de idea de solución:</span>
          </label>                    
          <div id="collapse-aa" class="panel-collapse collapse in">
            <div class="panel-body">
              <p>Considerando el objeto de la presente convocatoria, autorizamos a La Cámara de Comercio de Armenia y del Quindío, a dar a conocer y difundir la postulación de la presente solución en los datos establecidos sin que se comprometa información técnica detallada. Esta información podrá circular por cualquier medio de comunicación masivo o personalizado.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>