<?php $obj = $this->datos; ?>
<div class="box-header navbar-inner">
	<h3><button class="btn btn closeform" title="Atras"><i class="icon-step-backward"></i></button><span class="break"></span> Información de Qué riesgos técnicos o de funcionalidad se pueden presentar cuando la solución esté completamente implementada</h3>
    <div class="box-icon btn-group">
    	<button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>
    </div>
</div>
<div class="box-content">
	<table class="table table-condensed table-striped">
	<?php if ($this->datos->getSolucionador() > 0 ): ?>
		<tr>
			<td>
				<b>Solucionador: </b></td>
			<td>
				<?php echo $this->datos->getSolucionadorObject()->get_Label_model(); ?>
			</td>
		</tr>
	<?php endif ?> 
		<tr>
			<td>
				<b>Nombre del riesgo: </b></td>
			<td>
			<?php echo $obj->getNombredelriesgo(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>Descripción : </b></td>
			<td>
			<?php echo $obj->getDescripcion(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>Probabilidad de ocurrencia : </b></td>
			<td>
			<?php echo $obj->getProbabilidad(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>impacto esperado, si se presenta : </b></td>
			<td>
			<?php echo $obj->getImpacto(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>Posibles medidas de prevención o mitigación: </b></td>
			<td>
			<?php echo $obj->getPrevencion(); ?>	
			</td>
		</tr>
	</table>
 </div>
