<table id="riesgostecnicosTable" class="table table-striped table-condensed " formBuscar="riesgostecnicosformbuscar" >
<thead >
	<tr>
		<th class="">Nombre del riesgo</th>
		<th class="hidden-phone">Descripción </th>
		<th class="hidden-phone">Probabilidad de ocurrencia </th>
		<th class="hidden-phone">impacto esperado, si se presenta </th>
		<th class="hidden-phone">Posibles medidas de prevención o mitigación</th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getNombredelriesgo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getDescripcion(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getProbabilidad(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getImpacto(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getPrevencion(); ?>	
		</td>
		<?php if (false) { ?>
		<td class="no-print" >
		  <div class="btn-group" title="<?php echo $obj->get_Label_Model() ?>">
			<?php if($this->permisos["edit"]  ): ?>
				<button title="Editar" class="btn btn-success loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/riesgostecnicos/edit/id/<?php echo $obj->getId() ?>" ><i class="icon-pencil"></i></button>
			<?php endif ?>
			<?php if($this->permisos["detail"] ): ?>
				<button title="Detalles" class="btn btn-info loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/riesgostecnicos/detail/id/<?php echo $obj->getId() ?>"><i class="icon-fullscreen"></i></button>
			<?php endif ?>
			<?php if($this->permisos["delete"]  ): ?>
				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/riesgostecnicos/delete/id/<?php echo $obj->getId() ?>"><i class="icon-trash"></i></button>
			<?php endif ?>
            </div>
		</td>
		<?php } ?>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>