<a data-toggle="modal" id="addnewriesgostecnicos" href="#newriesgostecnicos" class="btn btn-primary bg-color-4 pull-right addaction" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/add<?php echo $this->filterreceived; ?>" > <i class="fa fa-plus"></i> Agregar</a>

<table id="riesgostecnicosTable" class="table table-striped table-condensed " formBuscar="riesgostecnicosformbuscar" >
<thead >
	<tr>
		<th class="">Nombre del riesgo</th>
		<th class="hidden-phone">Descripcion</th>
		<th class="hidden-phone">Probabilidad</th>
		<th class="hidden-phone">Impacto</th>
		<th class="hidden-phone">Prevencion</th>
		<th style=" width: 74px;"></th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getNombredelriesgo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getDescripcion(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getProbabilidad(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getImpacto(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getPrevencion(); ?>	
		</td>
		<td class="no-print pull-right" >

				<a data-toggle="modal" href="#newriesgostecnicos" class="btn btn-success editaction" title="Editar" type="button" iditem="<?php echo $obj->getId() ?>" request="<?php echo $this->baseUrl() ?>/reto/riesgostecnicos/listbyid/id/<?php echo $obj->getId() ?>" >&nbsp;&nbsp;<i class="fa fa-pencil"></i>&nbsp;&nbsp;</a>

				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/riesgostecnicos/delete/id/<?php echo $obj->getId() ?>">&nbsp;&nbsp;<i class="fa fa-trash"></i>&nbsp;&nbsp;</button>

		</td>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>

<!--  MODAL riesgostecnicos-->
  <div class="modal fade customModal" id="newriesgostecnicos" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-4 border-color-1">
            <h3 class="panel-title modtitle">Nuevo Riesgo Tecnico</h3>
          </div>
          <div class="panel-body">
            <form action="#" name="riesgostecnicosform" id="riesgostecnicosform" method="POST" role="form">
            	<!-- id hidden para la edicion -->
              <div class="form-group formField">
              	<input type="hidden" class="form-control" name="riesgostecnicos_id" id="riesgostecnicos_id">
              </div>
              <div class="form-group formField">
              	<input type="text" class="form-control" name="nombredelriesgo" id="nombredelriesgo" placeholder="Nombre del Riesgo">
              </div>
              <div class="form-group formField">
              	<input type="text" class="form-control" name="descripcion" id="descripcion" placeholder="Descripcion">
              </div>
              <div class="form-group formField">
                <select name="probabilidad" id="probabilidad" class="form-control" >
                  <option value="">Probabilidad</option>
                  <option value="improbable">Improbable</option>
                  <option value="posible">Posible</option>
                  <option value="probable">Probable</option>
                </select>
              </div>
              <div class="form-group formField">
                <select name="impacto" id="impacto" class="form-control" >
                  <option value="">Impacto</option>
                  <option value="alto">Alto</option>
                  <option value="medio">Medio</option>
                  <option value="bajo">Bajo</option>
                </select>
              </div>
              <div class="form-group formField">
              	<input type="text" class="form-control" name="prevencion" id="prevencion" placeholder="Prevencion">
              </div>
              <div class="form-group formField">
                <a id="saveriesgostecnicos" data-dismiss="modal" href="#newriesgostecnicos" class="btn btn-primary btn-block bg-color-3 border-color-3">Agregar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript"></script>