<?php
	header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
	header("Content-type:   application/x-msexcel; charset=utf-8");
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("content-disposition: attachment;filename=grupoevaluacion_". date("Y_m_d_H_i_s",time()).".xls");
?>
<table border="1" align="center">
	<thead >
		<tr><th colspan="3" style="font-weight: bold;font-style: italic;">Listado de Grupo evaluacion</th></tr>
		<tr style="background-color: #C4C9DF; color:black;">
			<th>Nombre</th>
			<th>Orden</th>
			<th>Peso</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->pagination as $key => $obj) : ?>
		<?php $class = fmod($key, 2) == 0 ? ' background-color: #F9F9F9;' : ''; ?>
		<tr style="<?php echo $class; ?>">
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getNombre(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getOrden(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getPeso(); ?>
			</td>
		</tr>
<?php endforeach; ?>
</tbody>	
</table>
