<script>
	$(document).ready(function(){
		$("#solucionadoresmodalbuscar").modal('hide');
		reloadgrid();
	});
	function solucionadoresindexexcel(){

		var form = $('form#solucionadoresformbuscar');
		if($('input#download').length == 0){
			form.append('<input type="hidden" id="download" name="download" value="1" />"');
		}
		var formData = form.serialize();
		$('form#solucionadoresformbuscar').submit();
		form.find('input#download').remove();
	}
</script>
<div id="solucionadoresindex" class="box  contentindex"  filterreceived="<?php echo $this->filterreceived; ?>" request="<?php echo $this->baseUrl() ?>/reto/solucionadores/index<?php echo $this->filterreceived; ?>">
    <div class="box-header navbar-inner">
        <h3><span class="hidden-phone"><i class="icon-align-justify"></i><span class="break"></span> Listado </span>Solucionadores</h3>
        <div class="box-icon btn-group">
                <a class="btn" type="button" title="Buscar"  href="#solucionadoresmodalbuscar" data-toggle="modal" > <i class="icon-search"></i> </a>
            <?php if($this->permisos["add"]): ?>
                <a id="newsolucionadores" href="#newsolucionadores" class="btn btn-info loadform" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionadores/add<?php echo $this->filterreceived; ?>" > <i class="icon-plus"></i></a>
            <?php endif ?>
                <button class="btn btn-warning" title="Descargar a Excel" onclick="solucionadoresindexexcel()" type="button"><i class="icon-download-alt"></i></button>
                <!-- <button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>-->
        </div>
    </div>
    <div class="box-content">
<table id="solucionadoresTable" class="table table-striped table-condensed " formBuscar="solucionadoresformbuscar" >
<thead >
	<tr>
		<th  class="sort hidden-phone" sort="nombredelaempresa" >Nombre de la empresa / persona natural</th>
		<th  class="sort hidden-phone" sort="personal" >Personal</th>
		<th  class="sort hidden-phone"  >Progreso</th>
		<th class="no-print" width="126px">Acciones</th>

	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination->_objects as $obj) : ?>
	<tr>
		<td class="hidden-phone">
			<?php echo $obj->getNombredelaempresa(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getPersonal(); ?>
		</td>
		</td>
		<td class="hidden-phone">
			[AsignarPorcentaje]
		</td>
		<td class="no-print" >
		  <div class="btn-group" title="<?php echo $obj->get_Label_Model() ?>">
			<?php if($this->permisos["edit"]  ): ?>
				<button title="Editar" class="btn btn-success loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionadores/edit/id/<?php echo $obj->getId() ?>" ><i class="icon-pencil"></i></button>
			<?php endif ?>
			<?php if($this->permisos["menulateral"] ): ?>
				<a title="Proceso" class="btn btn-inverse"   href="<?php echo $this->baseUrl() ?>/reto/solucionadores/menulateral/solucionadores_id/<?php echo $obj->getId() ?>"><i class="icon-cogs"></i></a>
			<?php endif ?>
			<?php if($this->permisos["detail"] ): ?>
				<button title="Detalles" class="btn btn-info loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionadores/detail/id/<?php echo $obj->getId() ?>"><i class="icon-fullscreen"></i></button>
			<?php endif ?>
			<?php if($this->permisos["delete"]  ): ?>
				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionadores/delete/id/<?php echo $obj->getId() ?>"><i class="icon-trash"></i></button>
			<?php endif ?>
            </div>
		</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>
    <?php echo $this->paginationControl($this->pagination,'Sliding','pagination.phtml');?>
    </div>
		<div class="modal hide" id="solucionadoresmodalbuscar">
		    <div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
		    <h3>Buscar</h3>
		    </div>
		    <div class="modal-body">
				<?php echo $this->formBuscar;?>
			</div>
			<div class="modal-footer">
			</div>
		</div>
</div>
