<?php $obj = $this->datos; ?>
<div class="box-header navbar-inner">
	<h3><button class="btn btn closeform" title="Atras"><i class="icon-step-backward"></i></button><span class="break"></span> Información de Qué otros desarrollos complementarios se deben realizar, para una optima implementación de la solución.</h3>
    <div class="box-icon btn-group">
    	<button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>
    </div>
</div>
<div class="box-content">
	<table class="table table-condensed table-striped">
		<tr>
			<td>
				<b>Desarrollo complementario requerido: </b></td>
			<td>
			<?php echo $obj->getDesarrollocomplementario(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>¿Por qué se requiere este desarrollo?: </b></td>
			<td>
			<?php echo $obj->getPorque(); ?>	
			</td>
		</tr>
	<?php if ($this->datos->getSolucionador() > 0 ): ?>
		<tr>
			<td>
				<b>Solucionador: </b></td>
			<td>
				<?php echo $this->datos->getSolucionadorObject()->get_Label_model(); ?>
			</td>
		</tr>
	<?php endif ?> 
	</table>
 </div>
