<?php
	header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
	header("Content-type:   application/x-msexcel; charset=utf-8");
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("content-disposition: attachment;filename=otrosdesarrollos_". date("Y_m_d_H_i_s",time()).".xls");
?>
<table border="1" align="center">
	<thead >
		<tr><th colspan="2" style="font-weight: bold;font-style: italic;">Listado de Qué otros desarrollos complementarios se deben realizar, para una optima implementación de la solución.</th></tr>
		<tr style="background-color: #C4C9DF; color:black;">
			<th>Desarrollo complementario requerido</th>
			<th>¿Por qué se requiere este desarrollo?</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->pagination as $key => $obj) : ?>
		<?php $class = fmod($key, 2) == 0 ? ' background-color: #F9F9F9;' : ''; ?>
		<tr style="<?php echo $class; ?>">
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getDesarrollocomplementario(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getPorque(); ?>
			</td>
		</tr>
<?php endforeach; ?>
</tbody>	
</table>
