<a data-toggle="modal" id="addnewotrosdesarrollos" href="#newotrosdesarrollos" class="btn btn-primary bg-color-4 pull-right addaction" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/add<?php echo $this->filterreceived; ?>" > <i class="fa fa-plus"></i> Agregar</a>

<table id="otrosdesarrollosTable" class="table table-striped table-condensed " formBuscar="otrosdesarrollosformbuscar" >
<thead >
	<tr>
		<th class="">Desarrollo complementario</th>
		<th class="hidden-phone">Por qué</th>
		<th style=" width: 74px;"></th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getDesarrollocomplementario(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getPorque(); ?>	
		</td>
		<td class="no-print pull-right" >

				<a data-toggle="modal" href="#newotrosdesarrollos" class="btn btn-success editaction" title="Editar" type="button" iditem="<?php echo $obj->getId() ?>" request="<?php echo $this->baseUrl() ?>/reto/otrosdesarrollos/listbyid/id/<?php echo $obj->getId() ?>" >&nbsp;&nbsp;<i class="fa fa-pencil"></i>&nbsp;&nbsp;</a>

				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/otrosdesarrollos/delete/id/<?php echo $obj->getId() ?>">&nbsp;&nbsp;<i class="fa fa-trash"></i>&nbsp;&nbsp;</button>

		</td>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>

<!--  MODAL otrosdesarrollos-->
  <div class="modal fade customModal" id="newotrosdesarrollos" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-4 border-color-1">
            <h3 class="panel-title modtitle">Nueva Caracteristica Principal Implementacion</h3>
          </div>
          <div class="panel-body">
            <form action="#" name="otrosdesarrollosform" id="otrosdesarrollosform" method="POST" role="form">
            	<!-- id hidden para la edicion -->
              <div class="form-group formField">
              	<input type="hidden" class="form-control" name="otrosdesarrollos_id" id="otrosdesarrollos_id">
              </div>
              <div class="form-group formField">
                <textarea name="desarrollocomplementario" id="desarrollocomplementario" placeholder="Desarrollo Complementario" class="form-control" style="height: 65px;"></textarea>
              </div>
              <div class="form-group formField">
                <textarea name="porque" id="porque" placeholder="Por qué" class="form-control" style="height: 65px;"></textarea>
              </div>
              <div class="form-group formField">
                <a id="saveotrosdesarrollos" data-dismiss="modal" href="#newotrosdesarrollos" class="btn btn-primary btn-block bg-color-3 border-color-3">Agregar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript"></script>