<!DOCTYPE html>
<html lang="en">
	<head>
	 	<?php echo $this->headTitle(); ?>
	    <?php echo $this->headMeta(); ?>
	    <?php echo $this->headLink(); ?>
	    <?php echo $this->headStyle(); ?>
		<?php echo $this->headScript (); ?>

		<link href="<?php echo $this->baseUrl() ?>/css/bootstrap.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl() ?>/css/font-awesome.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl() ?>/css/bootstrap-responsive.css" rel="stylesheet">		
		<link href="<?php echo $this->baseUrl() ?>/css/login.css" rel="stylesheet">
	</head>	
	<body>		
		<div class="container body">
			<div class="row-fluid ">
				<div class="span5 ">
					<div class="logo_container">
							<img width="200px" src="<?php echo $this->baseUrl() ?>/img/logo.png">
					</div>
				</div>
				<div class="span7 login_form">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
		</div>
  </body>
</html>	
