<!DOCTYPE html>
<html lang="es">
<head>

  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Retos - San Andres</title>
  
  <!-- PLUGINS CSS STYLE -->
  <link href="<?php echo $this->baseUrl() ?>/plugins/jquery-ui/jquery-ui.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl() ?>/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl() ?>/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/css/settings.css" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/selectbox/select_option1.css">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/owl-carousel/owl.carousel.css" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/isotope/jquery.fancybox.css">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope.css">
  
  <!-- GOOGLE FONT -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis:400,300,600,700' rel='stylesheet' type='text/css'>

  <!-- CUSTOM CSS -->
  <link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet">
  <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/colors/default.css" id="option_color">

  <!-- Icons -->
  <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/img/favicon.png">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body class="body-wrapper ">

  <div class="main-wrapper">  
    <!-- HEADER -->
    <header id="pageTop" class="header-wrapper ">
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar top-fixed clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>

      <!-- TOP INFO BAR -->
      <div class="top-info-bar bg-color-7 hidden-xs">
        <div class="container">
          <div class="row">
            <div class="col-sm-10">
              <ul class="list-inline topList">
                <li><i class="fa fa-envelope bg-color-1" aria-hidden="true"></i> <a href="mailto:info@yourdomain.com">info@yourdomain.com</a></li>
                <li><i class="fa fa-phone bg-color-2" aria-hidden="true"></i> +1 234 567 8900</li>
              </ul>
            </div>
            <div class="col-sm-2">
              <ul class="list-inline functionList">
                <li><i class="fa fa-unlock-alt bg-color-5" aria-hidden="true"></i> <a href='#loginModal' data-toggle="modal" >Login</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- NAVBAR -->
      <nav id="menuBar" class="navbar navbar-default lightHeader" role="navigation">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index-v3.html"><img src="img/logo-enlace.png" alt="logo"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active dropdown singleDrop color-1">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-home bg-color-1" aria-hidden="true"></i> <span>Inicio</span>
                </a>
              </li>
              <li class="dropdown singleDrop color-3">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-list-ul bg-color-3" aria-hidden="true"></i> <span>Páginas</span></a>
                <ul class="dropdown-menu dropdown-menu-left">
                  <li><a href="about_us.html">Acerda de</a></li>
                  <li><a href="about_us.html">Equipo</a></li>
                  <li><a href="about_us.html">Eventos</a></li>
                </ul>
              </li>
              <li class=" dropdown megaDropMenu color-2">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">
                  <i class="fa fa-file-text-o bg-color-2" aria-hidden="true"></i> 
                  <span>Retos</span>
                </a>
              </li>
              <li class="dropdown singleDrop color-5">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-calendar bg-color-5" aria-hidden="true"></i> 
                  <span>Calendario</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- BANNER -->
    <section class="bannercontainer bannercontainerV3">
      <div class="fullscreenbanner-container">
        <div class="fullscreenbanner">
          <ul>
            <li data-transition="fade" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
              <img src="img/sanandres/isla.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start"
                  data-hoffset="0"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Agua Potable a Peso
                </div>

                <div class="tp-caption rs-caption-2 sft"
                  data-hoffset="0"
                  data-y="345"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  ¿Cómo minimizar el impacto que tienen la energía y la fuente de agua en el costo de potabilización del agua de San Andrés? 
                </div>

                <div class="tp-caption rs-caption-3 sft"
                  data-hoffset="0"
                  data-y="455"
                  data-speed="1200"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <a href="#" class="btn btn-primary">ver más</a>
                </div>
              </div>
            </li>
            <li data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
              <img src="img/sanandres/isla.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Agua Potable a Peso
                </div>

                <div class="tp-caption rs-caption-2 sft text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="345"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                   ¿Cómo minimizar el impacto que tienen la energía y la fuente de agua en el costo de potabilización del agua de San Andrés?
                </div>

                <div class="tp-caption rs-caption-3 sft text-center"
                  data-hoffset="0"
                   data-x="center"
                  data-y="455"
                  data-speed="1200"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <a href="#" class="btn btn-primary">ver más</a>
                </div>
              </div>
            </li>
            <li data-transition="fade" data-slotamount="5" data-masterspeed="700"  data-title="Slide 3">
              <img src="img/sanandres/isla.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start text-right"
                  data-hoffset="0"
                  data-y="270"
                  data-x="right"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Agua Potable a Peso
                </div>

                <div class="tp-caption rs-caption-2 sft text-right"
                  data-hoffset="0"
                  data-x="right"
                  data-y="345"
                  data-x="right"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                   ¿Cómo minimizar el impacto que tienen la energía y la fuente de agua en el costo de potabilización del agua de San Andrés?
                </div>

                <div class="tp-caption rs-caption-3 sft text-right"
                  data-hoffset="0"
                  data-x="right"
                  data-y="455"
                  data-speed="1200"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <a href="#" class="btn btn-primary">ver más</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </section>

    <!-- WHITE SECTION -->
    <section class="whiteSection full-width clearfix eventSection" id="ourEvents">
      <div class="container">
        <div class="sectionTitle text-center">
          <h2>
            <span class="shape shape-left bg-color-4"></span>
            <span>Retos</span>
            <span class="shape shape-right bg-color-4"></span>
          </h2>
        </div>
          
        <div class="row">
          <div class="col-sm-6 col-xs-12 block">
            <div class="media eventContent bg-color-1">
              <div class="media-left">
                <img class="media-object" src="img/home/event/event-1.jpg" alt="Image">
                <span class="sticker-round">Activo</span>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><a href="single-event-left-sidebar.html">Agua Potable a Peso</a></h3>
                <ul class="list-unstyled">
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 2 de febrero</li>
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de febrero</li>
                </ul>
                <p>Proactiva San Andrés quiere reducir el costo de la potabilización del agua </p>
                <ul class="list-inline btn-yellow">
                  <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-xs-12 block">
            <div class="media eventContent bg-color-2">
               <div class="media-left">
                <img class="media-object" src="img/home/event/event-2.jpg" alt="Image">
                <span class="sticker-round">Pendiente</span>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><a href="single-event-left-sidebar.html">Reto 2</a></h3>
                <ul class="list-unstyled">
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 2 de febrero</li>
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de febrero</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
                <ul class="list-inline btn-green">
                  <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-xs-12 block">
            <div class="media eventContent bg-color-3">
              <div class="media-left">
                <img class="media-object" src="img/home/event/event-3.jpg" alt="Image">
                <span class="sticker-round bg-color-3">Cerrado</span>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><a href="single-event-left-sidebar.html">Nunc suscipit sem et.</a></h3>
                <ul class="list-unstyled">
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 1 de Enero</li>
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de Enero</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
                <ul class="list-inline btn-red">
                  <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-xs-12 block">
            <div class="media eventContent bg-color-4">
               <div class="media-left">
                <img class="media-object" src="img/home/event/event-4.jpg" alt="Image">
                <span class="sticker-round">Pendiente</span>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><a href="single-event-left-sidebar.html">Reto n</a></h3>
                <ul class="list-unstyled">
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Inicia 1 de Enero</li>
                  <li><i class="fa fa-calendar-o" aria-hidden="true"></i>Termina 4 de Enero</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
                <ul class="list-inline btn-sky">
                  <li><a href="reto-single-right-sidebar.html" class="btn btn-primary">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- COLOR SECTION -->
    <section class="colorSection full-width clearfix bg-color-4 teamSection">
      <div class="container">
        <div class="sectionTitle text-center alt">
          <h2>
            <span class="shape shape-left"></span>
            <span>Meet Our Staff</span>
            <span class="shape shape-right"></span>
          </h2>
        </div>
          
        <div class="row">
          <div class="col-xs-12">
            <div class="owl-carousel teamSlider">
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-1.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Smith</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-2.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-3.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-4.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-1.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-2.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-3.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
              <div class="slide">
                <div class="teamContent">
                  <div class="teamImage">
                    <img src="img/home/team/team-4.jpg" alt="img" class="img-circle">
                    <div class="maskingContent">
                      <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="teamInfo">
                    <h3><a href="teachers-details.html">Amanda Stone</a></h3>
                    <p>English Teacher</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <!-- COUNT UP SECTION-->
    <section class="countUpSection">
      <div class="container">
        <div class="sectionTitleSmall">
          <h2>Algunos datos</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod</p>
        </div>
          
        <div class="row">
          <div class="col-sm-3 col-xs-12">
            <div class="text-center">
              <div class="counter">179</div>
              <div class="counterInfo bg-color-1">Events Held</div>
            </div>
          </div>
          <div class="col-sm-3 col-xs-12">
            <div class="text-center">
              <div class="counter">579</div>
              <div class="counterInfo bg-color-2">Happy Funs</div>
            </div>
          </div>
          <div class="col-sm-3 col-xs-12">
            <div class="text-center">
              <div class="counter">279</div>
              <div class="counterInfo bg-color-3">happy clients</div>
            </div>
          </div>
          <div class="col-sm-3 col-xs-12">
            <div class="text-center">
              <div class="counter">479</div>
              <div class="counterInfo bg-color-4">hours support</div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- FOOTER -->
    <footer>
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>
      <!-- FOOTER INFO AREA -->
      
      <!-- COPY RIGHT -->
      <div class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
              <ul class="list-inline">
                <li><a href="#" class="bg-color-1"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-2"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-3"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-4"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-5"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
              </ul>
            </div>
            <div class="col-sm-7 col-sm-pull-5 col-xs-12">
              <div class="copyRightText">
                <p>© 2016 Copyright Kidz School Bootstrap Template by <a href="https://www.iamabdus.com/">Abdus</a>.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <div class="scrolling">
    <a href="#pageTop" class="backToTop hidden-xs" id="backToTop"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
  </div>

  <!-- LOGIN MODAL -->
  <div class="modal fade customModal" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-1 border-color-1">
            <h3 class="panel-title">Login</h3>
          </div>
          <div class="panel-body">
            <form action="#" method="POST" role="form">
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="User name">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="form-group formField">
                <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Log in">
              </div>
              <div class="form-group formField">
                <p class="help-block"><a href="#">Forgot password?</a></p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- CREATE ACCOUNT MODAL -->
  <div class="modal fade customModal" id="createAccount" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-1 border-color-1">
            <h3 class="panel-title">Create  an account</h3>
          </div>
          <div class="panel-body">
            <form action="#" method="POST" role="form">
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="Name">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="User name">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="Phone">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Re-Password">
              </div>
              <div class="form-group formField">
                <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Register">
              </div>
              <div class="form-group formField">
                <p class="help-block">Allready have an account? <a href="#">Log in</a></p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/jquery-ui/jquery-ui.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/selectbox/jquery.selectbox-0.1.3.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/owl-carousel/owl.carousel.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/counter-up/jquery.counterup.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/jquery.fancybox.pack.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope-triger.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/countdown/jquery.syotimer.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/google-custom-map/google-map.js"></script>
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyAjUY8rnvqvQmnUvnztrDgnIpQTLxidt18&callback=initMap"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/velocity/velocity.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/smoothscroll/SmoothScroll.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/js/custom.js"></script>

</body>

</html>