<!DOCTYPE html>
<html lang="es">
<head>

  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Retos - Cámara de comercio de armenia y del quindío</title>

  <!-- PLUGINS CSS STYLE -->
  <link href="<?php echo $this->baseUrl() ?>/plugins/jquery-ui/jquery-ui.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl() ?>/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl() ?>/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/css/settings.css" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/selectbox/select_option1.css">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/owl-carousel/owl.carousel.css" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/isotope/jquery.fancybox.css">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope.css">

  <!-- GOOGLE FONT -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis:400,300,600,700' rel='stylesheet' type='text/css'>
  <!--<link href='https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'> -->

  <!-- CUSTOM CSS -->
  <link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet">
  <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/colors/default.css" id="option_color">

  <!-- Icons -->
  <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/img/favicon.png">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <style type="text/css">
      .error {
        color: rgba(156, 21, 21, 0.71)!important;
      }
      input[type="radio"] {
        height: 14px!important;
      }
  </style>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body class="body-wrapper ">

  <div class="main-wrapper">
    <!-- HEADER -->
    <header id="pageTop" class="header-wrapper ">
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar top-fixed clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>

      <!-- TOP INFO BAR -->
      <div class="top-info-bar bg-color-7 hidden-xs">
        <div class="container">
          <div class="row">
            <div class="col-sm-10">
              <ul class="list-inline topList">
                <li><i class="fa fa-envelope bg-color-1" aria-hidden="true"></i> <a href="mailto:info@yourdomain.com">retocamaraarmenia@corporacionenlace.org</a></li>
                <li><i class="fa fa-phone bg-color-2" aria-hidden="true"></i> Teléfono de contacto: 320 831 2489</li>
              </ul>
            </div>
            
            <?php 
            if(Zend_Auth::getInstance()->hasIdentity()){
              ?>
                <div class="col-sm-2">
              <ul class="list-inline functionList">
                <li><i class="fa fa-unlock-alt bg-color-3" aria-hidden="true"></i> <a href='<?php echo $this->baseUrl(); ?>/authentication/logout' data-toggle="modal" >Cerrar sesión</a></li>
              </ul>
            </div>
              <?php 
              
            }else{
              ?>
              <div class="col-sm-2">
              <ul class="list-inline functionList">
                <li><i class="fa fa-unlock-alt bg-color-5" aria-hidden="true"></i> <a href='<?php echo $this->baseUrl(); ?>/authentication/login' data-toggle="modal" >Iniciar Sesión</a></li>
              </ul>
            </div>
            <?php 
            }
            ?>
            
          </div>
        </div>
      </div>

      <!-- NAVBAR -->
      <nav id="menuBar" class="navbar navbar-default lightHeader" role="navigation">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->baseUrl() ?>"><img src="<?php echo $this->baseUrl() ?>/img/logocamaraarmenia.png" alt="logo"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
            <?php  
            $auth = new Zend_Session_Namespace('veoliaZend_Auth');
            $rol = Zend_Registry::get('role');

              if($auth->_acl->isAllowed($rol,"reto:reto","index")){
                ?>
                 <li class="active dropdown singleDrop color-3">
                  <a href="<?php echo $this->baseUrl()?>/reto/reto" >
                    <i class="fa fa-fire bg-color-3" ></i> <span> Retos </span>
                  </a>
                </li>
                <?php 
                }
            ?>
            <?php  
              if($auth->_acl->isAllowed($rol,"reto:solucionadores","index")){
                ?>
                <li class="active dropdown singleDrop color-1">
                  <a href="<?php echo $this->baseUrl()?>/reto/solucionadores" >
                    <i class="fa fa-lightbulb-o bg-color-1" ></i> <span> Soluciones </span>
                  </a>
                </li>
                <?php 
                }
            ?>
            <?php  
              if($auth->_acl->isAllowed($rol,"default:aclusuarios","index")){
                ?>
                 <li class="active dropdown singleDrop color-5">
                  <a href="<?php echo $this->baseUrl()?>/default/aclusuarios" >
                    <i class="fa fa-user bg-color-5" ></i> <span> Administrar </span>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="<?php echo $this->baseUrl()?>/default/aclusuarios">Usuarios</a></li>
                    <li><a href="<?php echo $this->baseUrl()?>/default/aclroles">Roles</a></li>
                  </ul>
                </li>
                <?php 
                }
            ?>
            </ul>
          </div>
        </div>
      </nav>
    </header>

      <?php echo $this->layout()->content; ?>

    <!-- FOOTER -->
    <footer>
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>
      <!-- FOOTER INFO AREA -->

      <!-- COPY RIGHT -->
      <div class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
              <!-- <ul class="list-inline">
                <li><a href="#" class="bg-color-1"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-2"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-3"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-4"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-5"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
              </ul> -->
            </div>
            <div class="col-sm-7 col-sm-pull-5 col-xs-12">
              <div class="copyRightText">
                <p>© 2017 Copyright Corporación enlace.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <div class="scrolling">
    <a href="#pageTop" class="backToTop hidden-xs" id="backToTop"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
  </div>

  <!-- LOGIN MODAL -->
  <div class="modal fade customModal" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-1 border-color-1">
            <h3 class="panel-title">Login</h3>
          </div>
          <div class="panel-body">
            <form action="#" method="POST" role="form">
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="User name">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="form-group formField">
                <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Log in">
              </div>
              <div class="form-group formField">
                <p class="help-block"><a href="#">Forgot password?</a></p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- CREATE ACCOUNT MODAL -->
  <div class="modal fade customModal" id="createAccount" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-1 border-color-1">
            <h3 class="panel-title">Create  an account</h3>
          </div>
          <div class="panel-body">
            <form action="#" method="POST" role="form">
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="Name">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="User name">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" placeholder="Phone">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="form-group formField">
                <input type="password" class="form-control" placeholder="Re-Password">
              </div>
              <div class="form-group formField">
                <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Register">
              </div>
              <div class="form-group formField">
                <p class="help-block">Allready have an account? <a href="#">Log in</a></p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="notify"></div>
  <script src="<?php echo $this->baseUrl() ?>/plugins/jquery-ui/jquery-ui.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/selectbox/jquery.selectbox-0.1.3.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/owl-carousel/owl.carousel.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/counter-up/jquery.counterup.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/jquery.fancybox.pack.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/isotope/isotope-triger.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/countdown/jquery.syotimer.js"></script>
  <!-- <script src="<?php echo $this->baseUrl() ?>/plugins/google-custom-map/google-map.js"></script>
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyAjUY8rnvqvQmnUvnztrDgnIpQTLxidt18&callback=initMap"></script> -->
  <script src="<?php echo $this->baseUrl() ?>/plugins/velocity/velocity.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/plugins/smoothscroll/SmoothScroll.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/js/custom.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/js/jquery.validate.min.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/js/bootstrap-notify.js"></script>
  <script src="<?php echo $this->baseUrl() ?>/js/base.js"> </script>
  <script src="<?php echo $this->baseUrl() ?>/ckeditor/ckeditor.js"></script>
  <!-- <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>-->

</body>

</html>
