
<div class="sidebar-nav">
	<ul class="nav nav-stacked left-menu">
		<li title="Atras">
			<a href="<?php echo$this->baseUrl()?>/default/tipoagrupacion/index" >
				<span class="box">
					<i class="icon-arrow-left"></i>
				</span>
				<span class="hidden-tablet hidden-phone btn">Atras</span>
			</a>
		</li>
	<?php if($this->permisos["agrupacion"]): ?>
			<li class="navigation-index" title="Agrupaciones">
				<a rel="<?php echo$this->baseUrl()?>/default/agrupacion/index/tipoagrupacion_id/<?php echo $this->tipoagrupacion_id ?>"  href="#agrupacion_index" class="loadsubcontainer">
					<span class="box">
						<i class="icon-list"></i>
					</span>
					<span class="hidden-tablet hidden-phone">Agrupaciones</span>
				</a>
			</li>			
	<?php endif ?>	
	</ul>
</div>
<div  class="content-wrapper">
	<ul class="nav nav-tabs pull-right title-menulateral "><li class="active"><a><strong>Tipo de Agrupacion: <?php echo $this->object->get_Label_Model() ?></strong></a></li></ul>
	<div id="subcontainer">

	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){		
		$(".loadsubcontainer").click(function(event){
			event.preventDefault();
			show_loader();
			var currLocation = window.location.href;
			href = currLocation.split("?")[0]+'?sublink='+ $(this).attr("rel");
			history.pushState(null, "", href);
			$("#subcontainer").load($(this).attr("rel"), hide_loader);
			$(".navigation-index.active").removeClass("active");	
			$(this).parents(".navigation-index").addClass("active");
		});
		var currLocation = window.location.href;
		if(currLocation.split("?")[1] == undefined){
			var rel = $('.left-menu > li:first-child').next().children('a').attr("rel");
			var se = $('.left-menu > li:first-child').next();
			href = location.href+'?sublink='+ rel;
			history.replaceState(null, "", href);
			$("#subcontainer").load(rel, hide_loader);
			$(".navigation-index.active").removeClass("active");
			$(se).addClass("active");
		}else{
			if(currLocation.split("?")[1]){
				$(".navigation-index.active").removeClass("active");
				var tab = getUrlParameters("sublink", "", true)
				var currLocation = location.href;
				parArr = currLocation.split("?")[2];
				$("#subcontainer").load(tab+'?'+parArr);
				$('a[rel="'+tab+'"]').parent().addClass("active"); 
			}
		}
	});
</script>


