<?php $obj = $this->datos; ?>
<div class="box-header navbar-inner">
	<h3><button class="btn btn closeform" title="Atras"><i class="icon-step-backward"></i></button><span class="break"></span> Información de Roles</h3>
    <div class="box-icon btn-group">
    	<button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>
    </div>
</div>
<div class="box-content">
	<table class="table table-condensed table-striped">
		<tr>
			<td>
				<b>Nombre: </b></td>
			<td>
			<?php echo $obj->getRolnombre(); ?>	
			</td>
		</tr>
	<?php if ($this->datos->getRolpadre() > 0 ): ?>
		<tr>
			<td>
				<b>Padre: </b></td>
			<td>
				<?php echo $this->datos->getRolpadreObject()->get_Label_model(); ?>
			</td>
		</tr>
	<?php endif ?> 
	</table>
 </div>
