<div class="page-header">
    <h2>Editando Roles</h2>
</div>
<div id="formaclroles" > 
<?php echo $this->form; ?> 
</div>
<script>
$(document).ready(function(){
	loadpage(); 

	reloadaclroles();	
})
function clicksaveformaclroles()
{
    var buttonSelect = $(this); 
    buttonSelect.parents(".form-actions").find("button").button('loading');
    if ($("#aclrolesform").valid()) {
        $.post("<?php echo $this->baseUrl()?>/default/aclroles/edit", $("#aclrolesform").serialize(),
            function(data) {
                if (data.id<0) {
                    $("#aclrolesform").parent().html(data.form);                  
                    reloadaclroles();
                    buttonSelect.parents(".form-actions").find("button").button('reset');
                } else {
                    $('.notify').notify({message: { text: '  Registro actualizado con éxito ' }}).show();
                    show_loader();                        
                    var Request = "";
                    if (buttonSelect.attr("new") == "true") {
						var Content = buttonSelect.parents(".contenido");
                        Request = "<?php echo $this->baseUrl()?>/default/aclroles/add<?php echo $this->filterreceived?>";
                        Content.load(Request,function(response, status, xhr) {successload(response, status, xhr)});
                    } else {
                         history.back();
                         hide_loader();
                    }
                }
            }
        )
    } else {
        buttonSelect.parents(".form-actions").find("button").button('reset');
        alert("Formulario invalido");
    }
}
function reloadaclroles(){
	$("#submitaclroles").click(clicksaveformaclroles);
}
</script>
