<?php
	header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
	header("Content-type:   application/x-msexcel; charset=utf-8");
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("content-disposition: attachment;filename=itemaevaluar_". date("Y_m_d_H_i_s",time()).".xls");
?>
<table border="1" align="center">
	<thead >
		<tr><th colspan="5" style="font-weight: bold;font-style: italic;">Listado de Items a evaluar</th></tr>
		<tr style="background-color: #C4C9DF; color:black;">
			<th>Título</th>
			<th>Tabla</th>
			<th>columna</th>
			<th>Evaluable</th>
			<th>Orden</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->pagination as $key => $obj) : ?>
		<?php $class = fmod($key, 2) == 0 ? ' background-color: #F9F9F9;' : ''; ?>
		<tr style="<?php echo $class; ?>">
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getTitulo(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getTabla(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getColumna(); ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php if($obj->getEvaluable()==1)echo "Sí"; else echo "No"; ?>
			</td>
			<td style='mso-number-format:"@"'>
				<?php echo $obj->getOrden(); ?>
			</td>
		</tr>
<?php endforeach; ?>
</tbody>	
</table>
