<?php $obj = $this->datos; ?>
<div class="box-header navbar-inner">
	<h3><button class="btn btn closeform" title="Atras"><i class="icon-step-backward"></i></button><span class="break"></span> Información de Cuáles son las actividades fundamentales que se deben desarrolla en propuesta? </h3>
    <div class="box-icon btn-group">
    	<button class="btn btn-inverse" title="Imprimir" onclick="window.print();" type="button"> <i class="icon-print"></i></button>
    </div>
</div>
<div class="box-content">
	<table class="table table-condensed table-striped">
	<?php if ($this->datos->getSolucionador() > 0 ): ?>
		<tr>
			<td>
				<b>Solucionador: </b></td>
			<td>
				<?php echo $this->datos->getSolucionadorObject()->get_Label_model(); ?>
			</td>
		</tr>
	<?php endif ?> 
		<tr>
			<td>
				<b>Nombre de la actividad: </b></td>
			<td>
			<?php echo $obj->getActividades(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>Qué se espera obtener de esta actividad: </b></td>
			<td>
			<?php echo $obj->getResultadoactividad(); ?>	
			</td>
		</tr>
		<tr>
			<td>
				<b>Cuanto tiempo dura la actividad?: </b></td>
			<td>
			<?php echo $obj->getTiempoactividad(); ?>	
			</td>
		</tr>
	</table>
 </div>
