<a data-toggle="modal" data-target="#newactividadesfundamentales" id="addnewactividadesfundamentales" href="#newactividadesfundamentales" class="btn btn-primary bg-color-4 pull-right addaction" title="Nuevo" type="button" request="<?php echo $this->baseUrl() ?>/reto/reto/add<?php echo $this->filterreceived; ?>" > <i class="fa fa-plus"></i> Agregar</a>

<table id="actividadesfundamentalesTable" class="table table-striped table-condensed " formBuscar="actividadesfundamentalesformbuscar" >
<thead >
	<tr>
		<th class="">Nombre de la actividad</th>
		<th class="hidden-phone">Qué se espera obtener de esta actividad</th>
		<th class="hidden-phone">Cuanto tiempo dura la actividad</th>
		<th style=" width: 74px;"></th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getActividades(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getResultadoactividad(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getTiempoactividad(); ?>	
		</td>
		<td class="no-print pull-right" >

				<a data-toggle="modal" href="#newactividadesfundamentales" class="btn btn-success editaction" title="Editar" type="button" iditem="<?php echo $obj->getId() ?>" request="<?php echo $this->baseUrl() ?>/reto/actividadesfundamentales/listbyid/id/<?php echo $obj->getId() ?>" >&nbsp;&nbsp;<i class="fa fa-pencil"></i>&nbsp;&nbsp;</a>

				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/actividadesfundamentales/delete/id/<?php echo $obj->getId() ?>">&nbsp;&nbsp;<i class="fa fa-trash"></i>&nbsp;&nbsp;</button>

		</td>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>

<!--  MODAL actividadesfundamentales-->
  <div class="modal fade customModal" id="newactividadesfundamentales" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="panel panel-default formPanel">
          <div class="panel-heading bg-color-4 border-color-1">
            <h3 class="panel-title modtitle">Nueva Actividad Fundamental</h3>
          </div>

          <div class="panel-body">
            <form action="#" name="actividadesfundamentalesform" id="actividadesfundamentalesform" method="POST" role="form">
            	<!-- id hidden para la edicion -->
              <div class="form-group formField">
              	<input type="hidden" class="form-control" name="actividadesfundamentales_id" id="actividadesfundamentales_id">
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" name="actividades" id="actividades" placeholder="Nombre de la actividad">
              </div>
              <div class="form-group formField">
              	<textarea name="resultadoactividad" id="resultadoactividad" placeholder="Qué se espera obtener de esta actividad" class="form-control"></textarea>
                <!-- <input type="password" class="form-control" placeholder="Qué se espera obtener de esta actividad"> -->
              </div>
              <div class="form-group formField">
                <input type="text" class="form-control" name="tiempoactividad" id="tiempoactividad" placeholder="Cuanto tiempo dura la actividad">
              </div>
              <div class="form-group formField">
                <a id="saveactividadesfundamentales" data-dismiss="modal" href="#newactividadesfundamentales" class="btn btn-primary btn-block bg-color-3 border-color-3">Agregar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript"></script>