<div class="page-header">
    <h2>Editando  : <?php echo $this->object->get_Label_Model() ?> </h2>
</div>
<div id="formpassword" > 
<?php echo $this->form; ?> 
</div>
<script>
$(document).ready(function(){
    $('#username').on("change",function(){
		verificarunicousername();
    });
	loadpage(); 
	reloadaclusuarios();	
})



function clicksaveformaclusuarios()
{
	if(!verificarunicousername())return;
    var buttonSelect = $(this); 
    buttonSelect.parents(".form-actions").find("button").button('loading');
    if ($("#aclusuariosform").valid()) {
        $.post("<?php echo $this->baseUrl()?>/default/aclusuarios/password", $("#aclusuariosform").serialize(),
            function(data) {
                if (data.id<0) {
                    $("#aclusuariosform").parent().html(data.form);                  
                    reloadaclusuarios();
                    buttonSelect.parents(".form-actions").find("button").button('reset');
                } else {
                    $('.notify').notify({message: { text: '  Registro actualizado con éxito ' }}).show();
                    show_loader();                        
                    var Request = "";
                    if (buttonSelect.attr("new") == "true") {
						var Content = buttonSelect.parents(".contenido");
                        Request = "<?php echo $this->baseUrl()?>/default/aclusuarios/add<?php echo $this->filterreceived?>";
                        Content.load(Request,function(response, status, xhr) {successload(response, status, xhr)});
                    } else {
                         history.back();
                         hide_loader();
                    }
                }
            }
        )
    } else {
        buttonSelect.parents(".form-actions").find("button").button('reset');
        alert("Formulario invalido");
    }
}
    function verificarunicousername()
    {
        $("#submitaclusuarios").button('loading');
    	$("#saveandnewaclusuarios").button('loading');
		valor=$('#username').val();
		url='<?php echo$this->baseUrl()?>/default/aclusuarios/validateonly/propiedad/username/valor/'+valor;
		var data = ajaxasincronico(url);
		if(parseInt($('#aclusuarios_id').val()) == parseInt(data))
          return true;
		verificarunico(data,$('#username'));
		$("#submitaclusuarios").button('reset');
		$("#saveandnewaclusuarios").button('reset');
		if(data > 0)return false;else return true;
    }
function reloadaclusuarios(){
	$("#submitaclusuarios").click(clicksaveformaclusuarios);
}

</script>
