 <!-- MAIN SECTION -->
 <?php 
 if(isset($_GET['mensaje'])) {
    switch ($_GET['mensaje']) {
      case 'login':
        ?> <div class="col-xs-12 alert">
          <div class=" alert alert-danger alert-dismissible alt" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="false">x</span></button>
            <span class="successAlert dangerAlert"><i class="fa fa-remove" aria-hidden="true"></i></span>
            Debe registrarse o iniciar sesión para poder continuar
          </div>
        </div>
      <?php
        break;
      case 'error':
        ?> <div class="col-xs-12 alert">
          <div class=" alert alert-danger alert-dismissible alt" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="false">x</span></button>
            <span class="successAlert dangerAlert"><i class="fa fa-remove" aria-hidden="true"></i></span>
            Error en las credenciales verifique su usuario o contraseña
          </div>
        </div>
      <?php
        break;
      default:
        # code...
        break;
    }
  }
  ?>
    
    <section class="mainContent full-width clearfix">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-2 col-sm-6 col-xs-12">
            <div class="panel panel-default formPanel">
              <div class="panel-heading bg-color-1 border-color-1">
                <h3 class="panel-title">Crea una Cuenta</h3>
              </div>
              <div class="panel-body">

               <?php echo $this->form_nuevo; ?>
                <!-- <form action="<?php echo $this->baseUrl()?>/authentication/agregar/" method="POST" role="form">
                  <div class="form-group formField">
                    <input name="nombre" type="text" class="form-control" placeholder="Nombre">
                  </div>
                  <div class="form-group formField">
                    <input name="email" type="text" class="form-control" placeholder="Correo">
                  </div>
                  <div class="form-group formField">
                    <input name="password" type="password" class="form-control" placeholder="Contraseña">
                  </div>
                  <div class="form-group formField">
                    <input name="password0" type="password" class="form-control" placeholder="Repetir Contraseña">
                  </div>
                  <div class="form-group formField" >
                      <label>
                        <input type="checkbox"> He leído y acepto los <a href="<?php echo $this->baseUrl()?>/index/terminosycondiciones">términos y condiciones </a>
                      </label>
                  </div>
                  <div class="form-group formField">
                    <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Register">
                  </div> -->

                  <!-- <div class="form-group formField">
                    <p class="help-block">Allready have an account? <a href="#">Log in</a></p>
                  </div> -->
                </form>
              </div>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default formPanel">
              <div class="panel-heading bg-color-1 border-color-1">
                <h3 class="panel-title">¿Se encuentra registrado?</h3>
              </div>
              <div class="panel-body">
				<?php echo '<font color="red">'.$this->errorMessage.'</font>';?>
                <form action="<?php echo $this->baseUrl()?>/authentication/login/" method="POST" role="form">
                  <div class="form-group formField">
                    <input type="text" name="username" class="form-control" placeholder="Correo">
                  </div>
                  <div class="form-group formField">
                    <input type="password" name="password" class="form-control" placeholder="Contraseña">
                  </div>
                  <div class="form-group formField">
                    <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Log in">
                  </div>
                  <div class="form-group formField">
                   <!--  <p class="help-block"><a href="#">Forgot password?</a></p> -->
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <script type="text/javascript">
    $(document).ready(function() {
      
      
      $("#manejodedatos").after( '<label>&nbsp;&nbsp;He leído y acepto los <a href="<?php echo $this->baseUrl()?>/index/terminosycondiciones">términos y condiciones </a></label>');
    });
      
      function clickcrearusuario()
        {
            var buttonSelect = $(this); 
            buttonSelect.parents(".form-actions").find("button").button('loading');

            if ($("#aclusuariosform").valid()) {
                $.post("<?php echo $this->baseUrl()?>/aclusuarios/agregar/", $("#aclusuariosform").serialize(),
                    function(data) {
                      if(data.id>0){
                        alert('Usuario agregaro con éxito!  inicie session para continuar')
                      }else{
                         alert('Error al crear el ')
                      }
                      // html = '<div class="col-xs-12 message"><div class=" alert alert-success alert-dismissible alt" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="false">x</span></button><span class="successAlert"><i class="fa fa-check" aria-hidden="true"></i></span>Registro actualizado con éxito</div></div>';
                      //   if(data.success){
                      //     $(".panel-body").append(html);
                      //     $('.message').slideUp( 2000 );
                      //      setTimeout(function() {
                      //         $('.message').remove();
                      //       }, 2000);
                      //   }
                        
                    });
              } else {
                buttonSelect.parents(".form-actions").find("button").button('reset');
                alert("Formulario invalido");
            }
        }
    </script>
    <style type="text/css">
      .formField .form-control input.error, .error {
          border-color: #ea7066 !important;
          color: #ea7066 !important;
      }
    ]
      .formField .form-control {
          margin-top: 15px;
          margin-bottom: 5px;
      }
    </style>