<section class="mainContent full-width clearfix">
  <div class="container">
    <div class="row">
    	<div class="col-md-3 col-sm-2 col-xs-1">
    	</div>    	
    	<div class="col-md-6 col-sm-8 col-xs-10">
	    	<?php if ($this->errorMessage != "") {?>
					<div class="alert alert-warning">
					  <button type="button" class="close" data-dismiss="alert">&times;</button>
					  <strong>Ups!</strong> <?php echo $this->errorMessage; ?>
					</div>
				<?php }  ?>
				<?php if ($this->successMessage != "") {?>
					<div class="alert alert-success">
					  <strong>Yuhuu!</strong> <?php echo $this->successMessage; ?>
					</div>
					<br>
					<a href="<?php echo $this->baseUrl(); ?>/default/authentication/login/">Ingresar</a>
				<?php } else {  ?>
	        <div class="panel panel-default formPanel">
	          <div class="panel-heading bg-color-1 border-color-1">
	            <h3 class="panel-title">He olvidado mi contraseña...</h3>
	          </div>
	          <div class="panel-body">              
	            <form action="<?php echo $this->baseUrl()?>/authentication/recovery/" method="POST" role="form">
	              <div class="form-group formField">
	                <input type="text" name="email" id="email" value="" class="form-control" placeholder="Correo electrónico">
	              </div>
	              <div class="form-group formField">
	                <input type="submit" class="btn btn-primary btn-block bg-color-3 border-color-3" value="Recuperar contraseña">
	              </div>
	            </form>
	          </div>
	        </div>
				<?php } ?>
      </div>
      <div class="col-md-3 col-sm-2 col-xs-1">
    	</div>
		</div>
	</div>
</section>