<div class="page-header">
    <h2>Editando Qué soluciones similares a la presentada a la propuesta ha desarrollado recientemente</h2>
</div>
<div id="formsolucionessimilares" > 
<?php echo $this->form; ?> 
</div>
<script>
$(document).ready(function(){
	loadpage(); 

	reloadsolucionessimilares();	
})
function clicksaveformsolucionessimilares()
{
    var buttonSelect = $(this); 
    buttonSelect.parents(".form-actions").find("button").button('loading');
    if ($("#solucionessimilaresform").valid()) {
        $.post("<?php echo $this->baseUrl()?>/reto/solucionessimilares/edit", $("#solucionessimilaresform").serialize(),
            function(data) {
                if (data.id<0) {
                    $("#solucionessimilaresform").parent().html(data.form);                  
                    reloadsolucionessimilares();
                    buttonSelect.parents(".form-actions").find("button").button('reset');
                } else {
                    $('.notify').notify({message: { text: '  Registro actualizado con éxito ' }}).show();
                    show_loader();                        
                    var Request = "";
                    if (buttonSelect.attr("new") == "true") {
						var Content = buttonSelect.parents(".contenido");
                        Request = "<?php echo $this->baseUrl()?>/reto/solucionessimilares/add<?php echo $this->filterreceived?>";
                        Content.load(Request,function(response, status, xhr) {successload(response, status, xhr)});
                    } else {
                         history.back();
                         hide_loader();
                    }
                }
            }
        )
    } else {
        buttonSelect.parents(".form-actions").find("button").button('reset');
        alert("Formulario invalido");
    }
}
function reloadsolucionessimilares(){
	$("#submitsolucionessimilares").click(clicksaveformsolucionessimilares);
}
</script>
