<table id="solucionessimilaresTable" class="table table-striped table-condensed " formBuscar="solucionessimilaresformbuscar" >
<thead >
	<tr>
		<th class="">Solución desarrollada </th>
		<th class="hidden-phone">Año en el que se desarrolló la solución</th>
		<th class="hidden-phone">Quien la desarrolló</th>
		<th class="hidden-phone">Resultados obtenidos obtenidos </th>
		<th class="hidden-phone">¿Qué dificultades se presentaron durante el desarrollo de la solución?</th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getSoluciondesarrollada(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getAnodesarrollo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getQuienladesarrollo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getResultadosobtenidos(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getDificultadespresentadas(); ?>	
		</td>
		<?php if (false) { ?>
		<td class="no-print" >
		  <div class="btn-group" title="<?php echo $obj->get_Label_Model() ?>">
			<?php if($this->permisos["edit"]  ): ?>
				<button title="Editar" class="btn btn-success loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionessimilares/edit/id/<?php echo $obj->getId() ?>" ><i class="icon-pencil"></i></button>
			<?php endif ?>
			<?php if($this->permisos["detail"] ): ?>
				<button title="Detalles" class="btn btn-info loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionessimilares/detail/id/<?php echo $obj->getId() ?>"><i class="icon-fullscreen"></i></button>
			<?php endif ?>
			<?php if($this->permisos["delete"]  ): ?>
				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/solucionessimilares/delete/id/<?php echo $obj->getId() ?>"><i class="icon-trash"></i></button>
			<?php endif ?>
            </div>
		</td>
		<?php } ?>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>