<table id="caracteristicasprincipalesimplementacionTable" class="table table-striped table-condensed " formBuscar="caracteristicasprincipalesimplementacionformbuscar" >
<thead >
	<tr>
		<th class="">Atributo Básico (característica sin la cual la solución no existe)</th>
		<th class="hidden-phone">Tecnología que puede dar soporte a la existencia de este atributo</th>
		<th class="hidden-phone">Grado de dificultad para involucrar la tecnología a la información</th>
		<th class="hidden-phone">Explicación del grado de dificultad otorgado</th>
	</tr>
</thead>
<tbody>
<?php foreach ($this->pagination as $obj) : ?>
	<tr>
		<td class="">
			<?php echo $obj->getAtributobasicoObject()->get_Label_model(); ?>
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getEstadodeldesarrollo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getGradodeldesarrollo(); ?>	
		</td>
		<td class="hidden-phone">
			<?php echo $obj->getAspectospendientes(); ?>	
		</td>
		<?php if (false) { ?>
		<td class="no-print" >
		  <div class="btn-group" title="<?php echo $obj->get_Label_Model() ?>">
			<?php if($this->permisos["edit"]  ): ?>
				<button title="Editar" class="btn btn-success loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/caracteristicasprincipalesimplementacion/edit/id/<?php echo $obj->getId() ?>" ><i class="icon-pencil"></i></button>
			<?php endif ?>
			<?php if($this->permisos["detail"] ): ?>
				<button title="Detalles" class="btn btn-info loadform" type="button" request="<?php echo $this->baseUrl() ?>/reto/caracteristicasprincipalesimplementacion/detail/id/<?php echo $obj->getId() ?>"><i class="icon-fullscreen"></i></button>
			<?php endif ?>
			<?php if($this->permisos["delete"]  ): ?>
				<button title="Eliminar" class="btn btn-danger deleteaction" type="button" request="<?php echo $this->baseUrl() ?>/reto/caracteristicasprincipalesimplementacion/delete/id/<?php echo $obj->getId() ?>"><i class="icon-trash"></i></button>
			<?php endif ?>
            </div>
		</td>
		<?php } ?>
	</tr>
<?php endforeach; ?>
</tbody>	
</table>